version: '2'
services:
  camunda-postgres:
    image: postgres:9.6
    hostname: postgres
    domainname: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=camunda
      - POSTGRES_USER=camunda
      - POSTGRES_PASSWORD=camunda
    volumes:
      - ./integration-database-config.sql:/docker-entrypoint-initdb.d/setup.sql
    networks:
      - compose_camunda

networks:
  compose_camunda:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.163.252.0/16